# Generated by Django 6.0 on 2025-12-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название марки')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна производитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег (км)')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('transmission', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('robot', 'Роботизированная'), ('variator', 'Вариатор')], max_length=20, verbose_name='Коробка передач')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электрический'), ('hybrid', 'Гибрид')], max_length=20, verbose_name='Тип топлива')),
                ('engine_volume', models.FloatField(verbose_name='Объем двигателя (л)')),
                ('horsepower', models.IntegerField(verbose_name='Лошадиные силы')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_image', to='cars_image.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars_image.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобилей',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
