# Generated by Django 6.0 on 2025-12-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='cars.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='cars_purcha_status_e112fa_idx'), models.Index(fields=['user', 'created_at'], name='cars_purcha_user_id_93e6c1_idx')],
            },
        ),
    ]
